### ISSUE TITLE
Remove code duplicate

### ISSUE THREAD

**Issue by mayojava** [nisrulz/stackedhorizontalprogressbar#2]
Remove code duplicate from `StackedHorizontalProgressBar.java` class

**Comment by mayojava** [comment]
@nisrulz can you please create a `develop` branch. I done a fix for this by creating an `init()` function in the class. I need to create a PR to develop branch like you mentioned, but it does not exist yet.

**Comment by nisrulz** [comment]
@mayojava yes. Let me do that.

**Comment by mayojava** [comment]
@nisrulz link to PR https://github.com/nisrulz/stackedhorizontalprogressbar/pull/3
